### PR TITLE
build: run Travis against Linux and OS X

### PR DESCRIPTION
**Pull request by strawbrary**

### CODE REVIEW

**Comment by strawbrary** [comment]
Got the [repro](https://travis-ci.org/benmosher/eslint-plugin-import/jobs/126209318)!

**Comment by benmosher** [comment]
Ah, sweet! I didn't realize it was that simple. 

Can you rebase this commit against the `node-v6` branch? I think I've got it fixed over there so all the tests should pass, then I can merge this in.

**Comment by strawbrary** [comment]
Done!

**Comment by benmosher** [comment]
Thanks! though I didn't realize a few commits from `master` had snuck in, so I just cherry-picked the OS commit over to #273.

**Pull request closed without merging**
