### PR TITLE
`no-extraneous-dependencies`: add support/option for `peerDependencies` (#423)

### PR DESCRIPTION
**Pull request by jfmengels**
`no-extraneous-dependencies`: add support/option for `peerDependencies` (#423)

### CODE REVIEW

**Comment by jfmengels** [comment]
Modified so that peerDependencies is true by default

**Comment by jfmengels** [comment]
> Why the extra "electron" test?

Because I like copy-pasting and didn't notice I copied too much :smile: Removed :+1:

**Comment by benmosher** [comment]
:shipit:


Good on your end? I'm ready to merge once `master` is passing on Travis.

**Comment by jfmengels** [comment]
All good for me :+1:

**Comment by benmosher** [comment]
coverage should bump back up once the OSX builds complete. also the failures on the Travis/push build are fixed in `master`

**Pull request merged**
