### PR TITLE
Fixes `Cannot read property 'some' of undefined`

### LINKED ISSUE #842: TypeError: Cannot read property 'some' of undefined when `ast.comments` is missing on the AST
https://github.com/benmosher/eslint-plugin-import/blob/1377f55bc3d003519a74a89b048e11b20d53990e/src/ExportMap.js#L333
```js
ExportMap.parse = function (path, content, context) {
  // ...

  // attempt to collect module doc
  ast.comments.some(c => {
```

### PR DESCRIPTION
**Pull request by alexgorbatchev**
Closes #842

### CODE REVIEW

**Comment by alexgorbatchev** [comment]
Oddly, `master` currently has 28 failing tests. I checked that after this change there are sill 28 failing tests.

**Comment by ljharb** [comment]
hmm, I only get 1 failing test locally on master (which I'm fixing momentarily)

**Comment by ljharb** [comment]
@alexgorbatchev would you mind rebasing on top of latest master?

**Comment by alexgorbatchev** [comment]
Rebased. I think the tests are failing on Windows. Ran it OSX and it was as you said, just one. No failures on OSX after the rebase.

**Comment by ljharb** [comment]
We'll have to deal with the windows failures later I guess.

**Comment by alexgorbatchev** [comment]
Could you please publish this to NPM when you get a chance?

**Pull request merged**
