### PR TITLE
Fix packageDir array support

### LINKED ISSUE #1175: Bug: Multiple packageDirs in no-extraneous-dependencies
According to the docs, packageDirs accepts an array of paths, and (presumably) the package.json's found at all the paths have some effect.

In the current implementation, only the last element in the array is used.

This is because [`Object.assign()` is used](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-extraneous-dependencies.js#L45) to merge the dependencies found in each file. As `Object.assign()` performs a shallow merge, and the [extractDepFields function](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-extraneous-dependencies.js#L15-L22) adds default empty objects for fields that are not defined in `package.json`, every field ends up being overridden in each iteration.

I suggest that a deep merge be performed here instead of `Object.assign`.

### PR DESCRIPTION
**Pull request by pzhine**
Fixes #1175

### CODE REVIEW

**Comment by benmosher** [comment]
looks great! thanks!

**Comment by ljharb** [comment]
@benmosher this was merged while tests were failing, and now master is broken. This needs to be fixed or reverted.

**Comment by benmosher** [comment]
yeah, weird. the original commit built fine though. looks like some deep typescript dependency changed and is why the later (markdown-only) builds failed.

**Comment by robin-ambachtsheer** [comment]
When will this fix be published?

**Comment by afenton90** [comment]
Does this issue need picking up again? As it is broken in the current version of `master`. Happy to re-apply the fix?

**Comment by benmosher** [comment]
published! v2.15.0

**Pull request merged**
