### PR TITLE
Fix false positive with default import having a "default" property

### LINKED ISSUE #507: no-named-as-default-member false positive, with default export with 'default' property
The following produces the incorrect error;

```js
//bar.js
export default { 
  default: 'baz'
};
```

```js
//foo.js
import bar from './bar';

const qux = bar.default;
```
It's incorrectly noting that there is a named export named "default", following the suggestion would lead to this: `import bar, { default } from './bar` which is clearly not right, and I'd suggest not ever what you want to do in this situation. Perhaps that if the property is from the default export, special case allowing 'default' as a property of that export? 

**edit**: actually that would hold true for any named export, with a property of the same name as the export on it.

### PR DESCRIPTION
**Pull request by jquense**
Fixes #507

### CODE REVIEW

**Comment by jfmengels** [comment]
LGTM, thanks @jquense :)

**Comment by benmosher** [comment]
Indeed, thanks much for a high-quality PR! 😎

**Comment by jfmengels** [comment]
Only thing missing was adding thanks to yourself in the changelog, but we'll do that next time we update it ;)
(and also link to this PR in the changelog)
Thanks again!

**Comment by benmosher** [comment]
@jfmengels I got it in the rebase: https://github.com/benmosher/eslint-plugin-import/commit/0d98253ea3bc1c5998223cab7b1a095ba943b210#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR11 😁

Can't really blame folks for not wanting to thank themselves, I suppose... 😄

**Comment by jfmengels** [comment]
Truthfylly, I think it's odd to ask someone to thank themselves or add themselves to a contributors list. It's better done by the maintainers to show that your work is really appreciated :)

Btw, do you want to add a link to this PR in the changelog?

**Comment by jquense** [comment]
thanks y'all!

**Comment by benmosher** [comment]
@jfmengels maybe we should start doing the changelog update in the merge commit instead of the PR. that would be less merge-conflict-prone, too.

**Pull request closed without merging**
