### PR TITLE
[Fix] `order`: ignore requires in template literal

### LINKED ISSUE #1936: import/order complains about inline requires
Rule config:

```js
    'import/order': [
      'error',
      {
        groups: ['builtin', 'external', 'parent', 'sibling', 'index'],
        'newlines-between': 'never',
      },
    ],
```

Code:

```js
import React from 'react';
import PropTypes from 'prop-types';
import { createGlobalStyle, ThemeProvider } from 'styled-components';

export const GlobalStyle = createGlobalStyle`
  @font-face {
    font-display: swap;
    font-family: 'font-name';
    src: url(${require('../fonts/font-name.eot')});
    src: url(${require('../fonts/font-name.woff2')}) format('woff2'),
      url(${require('../fonts/font-name.woff')}) format('woff'),
      url(${require('../fonts/font-name.ttf')}) format('truetype');
  }
`
```

It complains about the newline after the `styled-components` import as well as a newline after the last inline require. Not 100% sure this is a bug, admittedly, but I thought it would excuse inline requires that aren't assigned based on [this](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#pass). Happy to just disable this rule on this file if needed.

### PR DESCRIPTION
**Pull request by golopot**
Fixes #1936.

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks! It seems like a more general fix is in order; the only requires that this rule should warn on are module-level requires, whether in a template literal or not.

**Comment by golopot** [comment]
It sounds great to only warn on module-level requires! Two cases are failing though:

```js
const bar = require('foo').bar
```
```js
const foo = require('foo')()
```

I add some handling for these two cases. If just for backward compatibility.

**Review by ljharb — APPROVED** [review]
Nice.

**Comment by ljharb** [comment]
Those are module-level requires, even tho they're immediately destructured. Thanks for handling them!

**Comment by mAAdhaTTah** [comment]
@golopot Thank you for fixing!

**Pull request merged**
