### PR TITLE
Automatically find webpack.config.babel.js

### PR DESCRIPTION
**Pull request by taion**
This automatically finds webpack configs with custom extensions, in addition to just loading them.

### CODE REVIEW

**Comment by benmosher** [comment]
rebased and merged, thanks!

**Comment by taion** [comment]
Thanks! Would you mind releasing this when you get a chance?

**Comment by benmosher** [comment]
Planning to tomorrow morning, just wanted to get the broken package from yesterday fixed and deployed and give it a day or so. The bad publish rattled me a little. 😅

**Comment by benmosher** [comment]
Just published as v0.2.4 😎

**Comment by taion** [comment]
Thanks!

**Pull request closed without merging**
