### PR TITLE
Enable `quotes` rule for eslint

### PR DESCRIPTION
**Pull request by singles**
I missed those quotes while doing other PR: https://github.com/benmosher/eslint-plugin-import/pull/245#discussion_r61135535 :)

Now it should be harder to miss that :)

### CODE REVIEW

**Comment by jfmengels** [comment]
LGTM :)
@benmosher is this something you didn't want to enforce by any chance?

**Comment by benmosher** [comment]
I just recently turned it off, actually. This is one of those rules that (from my perspective) is as controversial as it is arbitrary. 

Which is to say: fine with me to turn it back on. 😁

**Comment by jfmengels** [comment]
Let's merge this then?

**Comment by benmosher** [comment]
👍

**Pull request merged**
