### PR TITLE
v1.10.0

### PR DESCRIPTION
**Pull request by benmosher**
- [x] test locally against real code 
- [x] 300 github stars! 🎉
- [x] the ol' once-over from @jfmengels
- [x] tag in git
- [x] publish to npm

FYI, also just published v0.3.2 of the Webpack resolver this morning.

### CODE REVIEW

**Comment by jfmengels** [comment]
> 300 github stars! :tada:

Also reached 100.000 downloads this week!
image
http://www.npmtrends.com/eslint-plugin-import

I notice that #333 was fixed but not added to the changelog (or didn't find it). That might be worth adding.
Looks all good to me otherwise :+1:

**Comment by benmosher** [comment]
Yeah, #333 fix was isolated to the Node resolver, so its changlog was actually born to note it: https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/node/CHANGELOG.md

Not clear to me whether that should also be mentioned in the main change log. Node resolver is the default, but it's installed independently as a dependency, so upgrading to 1.10+ won't necessarily pick that up.

**Comment by benmosher** [comment]
Re: growth in downloads -- blowing my mind. I don't understand how it's still growing.

**Comment by jfmengels** [comment]
> Not clear to me whether that should also be mentioned in the main change log

It doesn't have to, but since you have to search in the project for the node resolver project and changelog, I think it would be nice to at least have a link to the changelog from the node resolver npm page.

> Re: growth in downloads -- blowing my mind. I don't understand how it's still growing.

I think `XO` just integrated it and released it, so that can account for a few thousand downloads. I guess people are simply starting to spread the word about the benefits and quality of the plugin, so kudos to you :)

That said, I wonder how many people use the project for the static analysis tools vs the stylistic rules (like `order`). I sure hope it's for the former, but considering the popularity of my plugin (finally declining! http://www.npmtrends.com/eslint-plugin-import-order :tada:) and the uptake this project had when I added it here, I'm not sure. Too bad we can't see any data about that...

**Comment by benmosher** [comment]
> That said, I wonder how many people use the project for the static analysis tools vs the stylistic rules (like order).

Me too, man. Though [this reaction](https://github.com/zertosh/eslint-plugin-dependencies/issues/1#issuecomment-219263080) made me wonder if it's getting less obvious that the static analysis stuff is available.

And the style rules are great, people want and love them. I don't use most of them, personally, but I get the desire. My focus is still the analysis, but I'm more than happy to support and distribute the style rules, too.

**Comment by jfmengels** [comment]
Oh, didn't expect that kind of comment. Again, hard to know if that is the case for a lot of developers.

I think we could refresh the plugin description in the README to put an extra emphasis on static analysis and the benefits it brings. It sells itself short now that there are plenty of static analysis tools.

IMO, the analysis rules are the primary value of the plugin, and the stylistic rules are secondary. But they could be used as bait for people to start using the project :smile:

**Pull request merged**
