### PR TITLE
Add 'always-and-inside-groups' value to order's newlines-between option to allow newlines inside import groups

### PR DESCRIPTION
**Pull request by giodamelio**
New option to allow newlines inside import groups. See #627.

### CODE REVIEW

**Comment by giodamelio** [comment]
@jfmengels Just wanted to ping you and check on the status of this. I would love to get it merged if everything is in order.

**Comment by giodamelio** [comment]
I just updated this to the current master, @benmosher, could you take a look at this?

**Comment by benmosher** [comment]
@giodamelio need @jfmengels to review, `order` is his baby 😄

**Comment by jfmengels** [comment]
Hey @giodamelio!
First of all, sorry for not replying earlier... Totally dropped the ball there.
Second of all, thanks a lot, this looks really good :)

The only thing I would like to see changed, is the new option name. In my mind, `newlines-between: "always-with-newlines"` means the same thing as `newlines-between: "always"`. Maybe `newlines-between: "always-and-inside-groups"` would be more explicit? What do you think?

(apart for this, this LGTM, and I'll fine with merging this)

**Comment by giodamelio** [comment]
`"always-and-inside-groups"` sounds good to me. Fix incoming.

**Comment by giodamelio** [comment]
Should be all good to go.

**Comment by jfmengels** [comment]
Thanks a lot @giodamelio! :tada:

**Pull request merged**
