### PR TITLE
Added no-self-import rule

### PR DESCRIPTION
**Pull request by just-paja**
New rule checks against importing from the current file. Ref #447.

First time working with eslint rules. Please review.

### CODE REVIEW

**Comment by benmosher** [comment]
I think this rule should leverage the [`resolve` infrastructure](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-unresolved.js#L20).

At least, if `resolve` comes back non-null, then the result should be compared with `context.getFilename()`. Then the resolver is responsible for things like missing extensions, aliases, `linklocal`s, etc.

**Comment by jfmengels** [comment]
This would be a cool rule to have!
Are you still up to work on this @just-paja? No worries if you're not :)

**Comment by just-paja** [comment]
Hey, sorry all, I completely forgot about this. @jfmengels, I will happily pass this to you.

**Comment by jfmengels** [comment]
Hey, no problem ;)
Not sure if/when I'll get to this. It's up for the taking if someone wants to have a go at it.

**Comment by giodamelio** [comment]
If it's all right with everyone. I would like to take a crack at this one.

**Comment by jfmengels** [comment]
Please do @giodamelio!

**Comment by giodamelio** [comment]
Awesome, I just opened #727.

**Pull request closed without merging**
