### PR TITLE
Release v1.8.1, webpack/0.2.5

### PR DESCRIPTION
**Pull request by benmosher**
Releasing bugfixes + minor improvements to core plugin + Webpack resolver.

#332 feels semver-minor because it's large, but in all likelihood it just hasn't impacted anyone before @jkimbo brought it up. So probably valid semver-patch.

Tasks:

- [x] acquire maiden LGTM from @jfmengels 
- [ ] squash + merge (@benmosher)
- [ ] create both tags (@benmosher)
- [ ] publish (@benmosher)

### CODE REVIEW

**Comment by jfmengels** [comment]
I think we should probably separate submodule changelogs. Either by putting the core module's changelog first, then the resolvers (with a "table of contents" at the top of the page), or in separate files (I would choose option one). And it would be nice to have the same diff links (`[1.8.1`]) for the submodules.

Though we can do this all at a late time, and this LGTM ;)

**Comment by benmosher** [comment]
Yeah, the resolvers have been kindof a pain in the changelog. Esp. because I can't create one of those diff links for a subtree (...right?).

I'd probably put them in their own file, but they have been changing somewhat infrequently so I haven't bothered. 😅

**Comment by jfmengels** [comment]
> I can't create one of those diff links for a subtree (...right?)

You could, if you prepend them with something like
```md
## [webpack-0.2.5] - 2016-05-23
[webpack-0.2.5]: ./foo
```

**Comment by jfmengels** [comment]
:tada:

**Comment by benmosher** [comment]
took long enough 😅

**Pull request merged**
