### PR TITLE
[no-internal-modules] allow importing @-scoped modules

### LINKED ISSUE #577: no-internal-modules treats `@org/package` as a violation
The `no-internal-modules` rule is incorrectly flagging `import async from '@org/async'` as a violation, but should probably be allowed.

### PR DESCRIPTION
**Pull request by spalger**
Fixes #577 by counting the steps that do not start with `@`

### CODE REVIEW

**Comment by jfmengels** [comment]
Thanks a lot for the fix @spalger!

**Comment by jfmengels** [comment]
@benmosher I think there are failing tests for the `exports` rule on master. Do you know of anything changing recently?

**Comment by spalger** [comment]
@jfmengels updated

**Comment by jfmengels** [comment]
Awesome, LGTM :)

@benmosher For the errors, seems like a dependency (a parser?) now considers some of the invalid test cases from `export` as invalid syntax. So that's all good, we just need to update the expected error message / change the parser for those tests to keep supporting other parsers that allow the syntax.

Anyway, nothing for you to worry for this PR @spalger ;)

**Comment by jfmengels** [comment]
We just merged the v2 branch, this needs to be rebased :s

**Comment by spalger** [comment]
I'm tethering, so I'd rather not pull all the new deps, but I think that should do it

**Comment by jfmengels** [comment]
Still LGTM, thanks for your patience on this!

**Pull request merged**
