### PR TITLE
Disallow more common require cases

### PR DESCRIPTION
**Pull request by lightsofapollo**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Makes: `var fs = require('fs');` illegal.

**Comment by benmosher** [comment]
Thanks for this! I think this makes sense, when I first added `no-require` I was torn about what to do with core modules, but I think the ecosystem has evolved such that this makes sense, now.

I made a few comments on the test changes you made; basically just want to enforce they both fail by moving from `valid` to `invalid` instead of just deleting the tests.

I can make the changes, but I figure it'd be a bit cleaner if you can add one more commit (or rewrite the existing one) and then I can merge wholesale.

**Comment by benmosher** [comment]
Actually, no worries. I'm knocking out the test/docs changes right now. I'll publish as 0.8.0 once tests pass. 😄

**Comment by benmosher** [comment]
Published! Thanks again! :+1:

**Comment by lightsofapollo** [comment]
Thanks!

**Pull request merged**
