### PR TITLE
 Fixed documentation for the default values for the `order` rule (fixes #601)

### LINKED ISSUE #601: Documented defaults for `import/order` groups are inaccurate
From the documentation for the `import/order` rule's "groups" option:

> The default value is ["builtin", "external", "internal", "parent", "sibling", "index"]

However, the rule's source file contains instead

``` js
const defaultGroups = ['builtin', 'external', 'parent', 'sibling', 'index']
```

where `internal` is missing. Not sure which of the two should be changed (I assume the source file), but this sent me on a wild goose chase this afternoon.

### PR DESCRIPTION
**Pull request by jfmengels**
Fixes #601, and replaces #608.

cc @ljharb

### CODE REVIEW

**Comment by jfmengels** [comment]
Hmm, looks like another dependency update breaking... Looking into it a bit.

Anyway, thanks @ljharb for your advice :)

**Comment by jfmengels** [comment]
Builds on master are broken, and the culprit is Babylon. I fixed the error and have made a PR over there https://github.com/babel/babylon/pull/170.

This is safe to merge, as it's just md files, but we'll need a new Babylon release before being able to have a working test suite. Tip: Do not remove your node_modules folder @benmosher :)

**Comment by hzoo** [comment]
@jfmengels released babylon@6.11.6

**Comment by jfmengels** [comment]
@hzoo Thanks! Tests are passing now :)

**Comment by benmosher** [comment]
rebased and merged via 024a8a7

**Comment by jfmengels** [comment]
Cool, thanks!

**Pull request closed without merging**
