### PR TITLE
No useless path segments

### PR DESCRIPTION
**Pull request by danny-andrews**

### CODE REVIEW

**Comment by ljharb** [comment]
I'm confused; why are we opening up a duplicate PR?

It would be far more preferable to add more people to the fork branch so that #912 can be added to, rather than cluttering the repo with another PR :-/

**Comment by danny-andrews** [comment]
@ljharb Sorry, I didn't know how to do that. 😬

**Comment by danny-andrews** [comment]
@ljharb What do you mean by "add more people to the fork branch"?

**Comment by ljharb** [comment]
@danny-andrews the original PR author, @graingert, can add you as a collaborator to their fork repo; that way you can push directly to the branch that the PR is based on, and thus update the original PR.

This isn't a hard requirement, of course - but it'd be nice to coordinate since @graingert is available :-)

**Comment by graingert** [comment]
Done

**Comment by danny-andrews** [comment]
Made my updates to #912

**Pull request closed without merging**
