### PR TITLE
Release v2.0.1

### PR DESCRIPTION
**Pull request by benmosher**
Sorry I've been AWOL, haven't gone through all the issues but I figure it'd be good to get this published at least.

@jfmengels: Let me know if I missed anything else that ought to be included as additional minor bugfixes.

- [x] @jfmengels 
- [ ] tag
- [ ] publish
- [ ] merge back to `master`

### CODE REVIEW

**Comment by jfmengels** [comment]
I'd like https://github.com/benmosher/eslint-plugin-import/pull/614 to get into this, it's a small thing.

**Comment by benmosher** [comment]
merged #614 into both this branch and `master` directly

**Comment by benmosher** [comment]
On resolvers: no need to publish them now, since they correctly declared their dependencies. Will probably release the Webpack one soon-ish since there are new features in PRs for it.

**Comment by jfmengels** [comment]
:+1: Sounds good

**Comment by sindresorhus** [comment]
Any chance you could release this? I just released a new XO version and now getting hit by this issue with Node.js 4 and npm@2. See: https://travis-ci.org/sindresorhus/alfy/jobs/166693052

```
Error: Failed to load plugin import: Cannot find module 'object-assign'
Referenced from: 
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/sindresorhus/alfy/node_modules/xo/node_modules/eslint-plugin-import/lib/rules/extensions.js:11:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by jfmengels** [comment]
@benmosher I don't mind doing it, but I don't know the process or whether there are subtleties to know about. Let me know if you want me to do it, and if so, whether I should just use `npm version patch && npm publish` or something else.

**Comment by benmosher** [comment]
Published. Sorry about the lag time, haven't had any open source maintenance time since going full 👨‍👩‍👦‍👦 mode. 😅

Should be back at it sometime next week, hopefully.

**Comment by sindresorhus** [comment]
No worries. Btw congrats on the new baby 😀

**Comment by jfmengels** [comment]
Thanks @benmosher :)

**Comment by benmosher** [comment]
😄

@jfmengels I'll put together a release steps document at some point. It's gotten a little more complicated than just npm version + publish, but not much more. Just need to write it down 😅

**Comment by sindresorhus** [comment]
I would recommend a `maintaining.md` file in the repo root. See how we did it in AVA: https://github.com/avajs/ava/blob/master/maintaining.md (Feel free to steal anything from there).

**Comment by benmosher** [comment]
@sindresorhus ah, cool, thanks! just seeing this after already committing `RELEASE.md`, but it probably should evolve into something like what you've got

**Pull request merged**
