### PR TITLE
Add setting for specifying internal module directories

### LINKED ISSUE #807: `import/order` fails to recognize internal import groups
I'm using [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) with [eslint-import-resolver-babel-module](https://github.com/tleunen/eslint-import-resolver-babel-module) to map imports from `~/<path>` to `src/<path>`:

In my ESLint config, the `import/order` rule is turned on using the following configuration:

```js
module.exports = {
  rules: {
    'import/order': [
      2,
      {
        groups: [
          'builtin',
          'external',
          'internal',
          ['parent', 'sibling', 'index'],
        ],
        'newlines-between': 'always',
      },
    ],
  },
};
```

Imports from `~/<path>`, I believe, should be classified as an internal import group separated from other groups by a newline. I'm not sure what the behaviour is here, but given the following code:

```js
import someNpmModule from 'some-npm-module';

import SomeComponent from '~/components/SomeComponent';
import someUtil from '~/utils/someUtil';
```

I'm receiving the following error:
```
   3:1   error  There should be at least one empty line between import groups  import/order
```

### PR DESCRIPTION
**Pull request by Whoaa512**
Closes #807

### CODE REVIEW

**Comment by jjshammas** [comment]
Any movement on this? Would love to have this feature so we can properly order the `import/order` rule.

**Comment by Whoaa512** [comment]
I don't have time to work on this in the next few months. 

@jjshammas Feel free to pick it up and make the necessary changes.

**Comment by ljharb** [comment]
@jjshammas please don’t make a duplicate PR; either post a link here to your branch and i can pull in the commits, or, @Whoaa512 can add you as a collaborator on their fork, and you can make changes directly there.

**Comment by stramel** [comment]
@ljharb Did you have any thought or preference on how you think it should handle `no-internal-modules`?

**Comment by robatwilliams** [comment]
Matching using folder name `startsWith` wouldn't identify an internal module imported from a sibling: `../anInternalModule`. Does it need to do something similar to `isExternalPath`?

New setting needs to be documented in the readme, and linked to from the "related" section of the order rule's docs page, as has been done with the `import/external-module-folders` setting.

**Comment by rodrigobdz** [comment]
@stramel Did you gain any insights into how to handle `no-internal-modules`?

**Comment by JuHwon** [comment]
fyi: this implementation does not work, when  configuring internal-module-folders with something like `src/`.

**Comment by benmosher** [comment]
closing on account of staleness + I would rather not add global settings just for this, would prefer the suggestion in [this comment](https://github.com/benmosher/eslint-plugin-import/issues/807#issuecomment-301077339)

**Pull request closed without merging**
