### PR TITLE
hotfix bump to v2.2.1 to allow install of node resolver 0.3.0

### PR DESCRIPTION
**Pull request by benmosher**
branched from tag and just updated `package.json`.

@ljharb: would love your 👀 on my semver 😅 want to make sure I didn't screw up before publishing

todo:
- [ ] tag after merge
- [ ] merge `release` back into `master`

### CODE REVIEW

**Comment by benmosher** [comment]
agh, wait. apparently I went around the normal release process for v2.2.0 and never tagged anything 😞

**Comment by jfmengels** [comment]
@benmosher Can we merge this now?

**Comment by benmosher** [comment]
oh dang, totally forgot about this! not good! 😳

**Comment by benmosher** [comment]
re-did it in master as just a ref to 0.3.1

**Comment by benmosher** [comment]
commit: d9b712ac7fd1fddc391f7b234827925c160d956f

**Pull request closed without merging**
