### PR TITLE
Rebase of PR #794 (fixes #793)

### LINKED ISSUE #793: import/order fails after updating a dependency (redux-saga)
When using `redux-saga@0.14.4` everything is fine
But fails when using `redux-saga@0.14.5`

I think the reason for this to fails is this PR: https://github.com/redux-saga/redux-saga/pull/895

-----

Error message:

`./userSaga import should occur before import of redux-saga/effects             import/order`

Code: 

```js
import { fork } from 'redux-saga/effects';

import connectionFlow from './userSaga';
```

### PR DESCRIPTION
**Pull request by SpainTrain**
https://github.com/benmosher/eslint-plugin-import/pull/794 appeared stalled, so I just updated it.  LMK what to do RE changelog and squashing.

@Ephys, LMK if you rebase #794 and I can just close this (*thank you* for creating this, I just didn't want to see it languish :) ).

Closes #793

---
This change is [Reviewable](https://reviewable.io/reviews/benmosher/eslint-plugin-import/907)

### CODE REVIEW

**Comment by ljharb** [comment]
It's not a good idea to open a replacement PR; if the collaborators want to continue it, *we* can push directly to that PR. Opening up a new one just clutters up the repo. A comment on the original PR would have been better.

**Comment by SpainTrain** [comment]
@ljharb 

In general, yes I agree.  However there was a comment 23 days ago and a comment similar to your suggestion 15 days ago in that PR,which neither have been responded to.  I understand maintainers are busy, so this was an attempt to minimize work for others.  For organizational purposes, I thought this was pretty well titled to indicate that it is an intentional dupe.

I am happy to follow house rules an any repo, but tend towards taking (even a small bit) of work off others' plate rather than add noise to a discussion.

Thanks!

**Comment by Ephys** [comment]
My apologies for my lack of response, what should I do to help sort this out? :)

I'm happy to close my PR in favor to this one, or merge your PR with mine. Whichever solution works best for you

**Comment by SpainTrain** [comment]
@Ephys the rebase is easy, so probably best all around to rebase yours if you can?  Thanks again.

**Pull request closed without merging**
