### PR TITLE
New group types

### PR DESCRIPTION
**Pull request by evless**
Hello! I stumbled upon an old PR - https://github.com/benmosher/eslint-plugin-import/pull/1076, but tests fell there. I forked it and repaired this moment.

### CODE REVIEW

**Comment by ljharb** [comment]
In the future, please post a link to your new commits on the original PR, and a maintainer will pull them in - now I have to keep 2 PRs in sync.

**Comment by jeffshaver** [comment]
@ljharb @evless  Any update on this? Would be nice to get this in. With TS choosing to move away from tslint, having this would allow us to make a group for Typescript path aliases which would be really nice.

**Comment by evless** [comment]
@jeffshaver I don't know. I'm also waiting for this PR to be merged. Now I use changes from my fork. :(

**Comment by ljharb** [comment]
See #1076; this PR will only be merged as part of that one, since it's a copy of it.

**Comment by benmosher** [comment]
FWIW I am working on having the resolver API float group types, but I'ma close this since it's locked already anyway

**Pull request closed without merging**
