### PR TITLE
Add nested namespace handling for TS

### PR DESCRIPTION
**Pull request by julien1619**
Relates to #1673

Add nested namespace declaration handling for Typescript.

### CODE REVIEW

**Comment by julien1619** [comment]
I have one more commit to add so please wait before merging. Thanks!

**Comment by ljharb** [comment]
@julien1619 when this is ready for review, and tests are passing, please mark the PR as such :-) thanks!

**Comment by julien1619** [comment]
I have one last thing to fix, it doesn't crash anymore but it fails to check properly an existing nested namespace (see the last commit with the test that is still failing).

**Comment by julien1619** [comment]
Done!

**Comment by djejaquino** [comment]
No releases with this one?

**Comment by ljharb** [comment]
@djejaquino nope, not yet. you get what you pay for :-) it will be released when the next release is ready, and when i have time to release it.

**Comment by djejaquino** [comment]
@ljharb I am sorry, did you find my question unpolite or something to come up with such roughness? It was a very simple question with no intention to demand something out of anyone.

**Comment by ljharb** [comment]
@djejaquino i apologize that I came off as rough; in general, asking for a release (especially after a mere 4 days) is indeed impolite, since it's making demands on an unpaid maintainer's time. It's especially complex during a global pandemic and widespread police lawlessness.

I will get it released as soon as possible.

**Comment by djejaquino** [comment]
@ljharb again, I did not ask for a release, I asked if there is a release.

You do it at your time, I could not care less as I was just evaluating this plugin to maybe use it on a customer project. 

Maybe it was a poor choice of words in one’s perspective, and ended up leading you thinking that way, but I am not really used to tiptoe around internet people.

While I appreciate the great job maintainers such as you do for the community, I guess that dealing with condescending people asking for free stuff could create an over sensitive subject for some, leading to misinterpretation.

Stay safe.

**Comment by ljharb** [comment]
Apologies for being sensitive about it. In general, you can click on the [merge commit](https://github.com/benmosher/eslint-plugin-import/commit/5cc31478a12c138b382e8efa97275db945b80562), and see if it’s included in any git tags, indicating it’s in a release.

**Comment by djejaquino** [comment]
100% my fault not checking that. Thanks for pointing it out.

**Pull request merged**
