### PR TITLE
Consider also resolve.fallback while resolving modules with webpack

### PR DESCRIPTION
**Pull request by yp**
Add [resolve.fallback](https://webpack.github.io/docs/configuration.html#resolve-fallback) to the paths used to resolve modules in webpack.

### CODE REVIEW

**Comment by benmosher** [comment]
Sweet, thanks! I wondered when this would come up. Thanks for skipping the issue and going straight for the PR! 😎

Can you add a note in the change log with a reference to this PR?

**Comment by yp** [comment]
For sure!
I'll add the note right now.

**Comment by benmosher** [comment]
There is a section of PR url definitions at the bottom, can you dupe the top one and update to 254?

https://github.com/benmosher/eslint-plugin-import/master/CHANGELOG.md#L148

**Comment by benmosher** [comment]
Fantastic, thanks!

**Pull request merged**
