### PR TITLE
Fix flow interface imports giving false-negative with `named` rule

### LINKED ISSUE #708: False positives when importing from flow-typed module declarations
Explicit imports from [flow-typed](https://github.com/flowtype/flow-typed) module declarations seem to yield false positives.

Example:

```js
import type { ActionCreators } from "redux"
// error  ActionCreators not found in 'redux'  import/named
```

The error should not appear because [flow can attach declared types to named modules via flow-typed or other library files](https://flowtype.org/docs/third-party.html#using-flow-typed), even if the modules themselves do not export those types. In the example above, redux does not export any types. Instead, a [flow-typed library](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/redux_v3.x.x/flow_v0.33.x-/redux_v3.x.x.js) handles the type declarations.

### PR DESCRIPTION
**Pull request by futpib**
This fixes #708 without ignoring all type imports.

### CODE REVIEW

**Comment by futpib** [comment]
No idea on that travis-ci error, seems unrelated to the changes in this PR.

**Comment by julienw** [comment]
It just needs a merge now, right ? ;)

**Comment by benmosher** [comment]
published with 2.6.1 👍🏻 thanks!

**Comment by athomann** [comment]
Looks like I'm still experiencing this issue in 2.7.0.

**Comment by SpainTrain** [comment]
@athomann we are seeing it also, but it may be a different issue (possibly https://github.com/benmosher/eslint-plugin-import/issues/616 ?) since `redux-form` >= 7 exports flow defs from the module itself.

To expound on that - for us, this works with flow but results in `named` error from eslint-plugin-import

```
import type {FormProps} from 'redux-form'
```

but this works and results in no eslint error

```
import type {FormProps} from 'redux-form/es/index.js.flow'
```

**Pull request merged**
