### PR TITLE
Remove `absolute-first` option from `imports-first`

### PR DESCRIPTION
**Pull request by singles**
See #259

### CODE REVIEW

**Comment by jfmengels** [comment]
LGTM, though I'm not sure when we'd want to merge this. There's a growing number of semver-major issues being opened, so if we can do them all in one swoop, that'd be nice.
Thanks a lot anyway @singles! :D

**Comment by singles** [comment]
Sure, no problem, it's BC break anyway :) 

One question though - do you think I should update docs and in place of `absolute-first` add something like:

> `absolute-first` option is not available anymore - you can get the same results using `order` rule

**Comment by jfmengels** [comment]
I could see a deprecated section from here to v2, but I think I would not keep it. Its useful, but I don't like having relics of the past in the readme/docs. There's a changelog for that.
I'm not totally against though, just a small personal preference.

**Comment by singles** [comment]
You're right, good idea with one `deprecated` section :)

**Comment by jfmengels** [comment]
That'd have to be a new PR then, and we'd put this one on hold until v2 is ready I'd say.

**Comment by benmosher** [comment]
👍 to all points. 

I'm tempted to do it pre-v2 since it was undocumented anyway, but no telling how widely it's in use so probably better to wait. 

Plus it doesn't hurt to have it, short term. This PR serves as a sufficient deprecation notice, I think.

**Comment by jfmengels** [comment]
> no telling how widely it's in use so probably better to wait.

I'd say let's stick with proper semver just in case. And maybe in the meantime we'll found out people don't want to use `order` for some reason and would like to stick with this option.

> This PR serves as a sufficient deprecation notice, I think.

I'd add a `deprecated` section in the documentation of the rule, and add it to the changelog. We can't expect users to find out about it in the GH issues.

**Comment by singles** [comment]
> I'm tempted to do it pre-v2 since it was undocumented anyway

Just a note: Actually, it was https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/imports-first.md:

> Providing `absolute-first` as an option will report any absolute imports (i.e. packages) that come after any relative imports:

**Comment by benmosher** [comment]
Weird, not sure how I hallucinated that it wasn't in there. Definitely should save for v2, then.

**Comment by sindresorhus** [comment]
> I'd say let's stick with proper semver just in case.

Strictly speaking, semver only applies to the public *documented* API, but I see no harm either leaving it for now.

**Pull request closed without merging**
