### PR TITLE
v1.9.0 bump

### PR DESCRIPTION
**Pull request by benmosher**
There are more things I had hoped to complete during this release, but it's been a while so probably best to ship what's done, first.

- [x] get the old once-over and signoff from @jfmengels 
- [x] tag
- [x] publish to `next`
- [ ] ~~give it a day~~
- [ ] ~~move to `latest`~~

officially broken, can't release as-is

### CODE REVIEW

**Comment by jfmengels** [comment]
Let's do this :)

**Comment by benmosher** [comment]
Once this goes green I'll move to master, but 1.9.0 is officially broken, so it will never move to `next` 😓 .

@lukeapage and @le0nik I need you two to provide feedback on my changes in e044e37, ideally in the form of additional tests.

**Comment by jfmengels** [comment]
What are the problems?

**Comment by lukeapage** [comment]
@benmosher a quick review of it looks good, i can try it out on our repo soon.

**Comment by lukeapage** [comment]
confirmed, it still works nicely for my use case (also the one I added a test for)

**Comment by benmosher** [comment]
@jfmengels the new custom resolver stuff tries to load actual Webpack instead of the Webpack resolver plugin, due to the original precedence order. 

Doesn't show up in tests because Webpack isn't installed, but it happened immediately when I tried it in my actual project. 😅

**Pull request merged**
