### PR TITLE
doc(no-relative-parent-imports): rename title

### PR DESCRIPTION
**Pull request by feychenie**
Renamed the title of this page to be the full name of the rule, like on the rest of the docs.

### CODE REVIEW

**Comment by feychenie** [comment]
Closing this pull request, making a new one

**Comment by ljharb** [comment]
Please reuse this one instead of making a new one.

**Comment by ljharb** [comment]
@feychenie could you check the "allow edits" box on the RHS of this PR?

**Comment by feychenie** [comment]
done

**Pull request merged**
