### PR TITLE
[Fix] `no-unresolved`: check import() 

### LINKED ISSUE #2024: no-unresolved does not check dynamic import
```js
import("./component-xxx");
```

if the "./component-xxx" does not exists, the rule should report an error.

seems a reasonable enhencement?

### PR DESCRIPTION
**Pull request by aladdin-add**
dynamic import has changed in estree

refs: https://github.com/estree/estree/issues/197

Fixes #2024

### CODE REVIEW

**Comment by aladdin-add** [comment]
> Require “Allow Edits” / Require “Allow Edits” (pull_request_target) 

I didn't see the option in the page. :-(

**Comment by ljharb** [comment]
This might be a duplicate of #2012.

I'll rebase this after landing that, and keep whatever I can.

**Comment by aladdin-add** [comment]
didn't notice that. seems this one is no longer needed, so it can be closed now.

**Comment by aladdin-add** [comment]
didn't notice that. so

**Comment by aladdin-add** [comment]
the "allow edits" seems working after transfering the repo to "aladdin-add" group.

**Comment by aladdin-add** [comment]
@ljharb ptal~

**Comment by ljharb** [comment]
@aladdin-add still looks like there's some test failures; can you take a look?

**Comment by aladdin-add** [comment]
sure, will do!

**Comment by aladdin-add** [comment]
the strange thing is: I was not able to repro it - it's working on my computer.

image
maybe it is related to the "Typescript"?

**Comment by ljharb** [comment]
What npm version are you using to install it? On node 10+, we're using npm 7 latest in CI.

**Comment by aladdin-add** [comment]
my local env:
node.js v16.1.0
npm: 7.12.1

> On node 10+, we're using npm 7 latest in CI.

I don't think so - there was an error when upgrading npm
https://github.com/benmosher/eslint-plugin-import/pull/2026/checks?check_run_id=2573212587#step:3:532

**Comment by ljharb** [comment]
While that’s concerning, node 15 and 16 would still ship with some version of npm 7. I’ll have to look into that failure separately.

**Comment by aladdin-add** [comment]
it seems not related to npm. I switched to npm v6.14.13, and the tests was not failing.

**Comment by aladdin-add** [comment]
it turns out the node.js/npm version is not as expected. (tested on my [fork](https://github.com/aladdin-add/eslint-plugin-import/pull/3/checks?check_run_id=2574344396))

image

**Comment by ljharb** [comment]
That's a problem that I thought I'd fixed :-/ i'll take a look at it on master.

**Comment by ljharb** [comment]
Fixed the tests in master, will rebase now.

**Pull request merged**
