### PR TITLE
import/resolver move out webpack reading and processing (#788)

### PR DESCRIPTION
**Pull request by mieszko4**
This pr is related to https://github.com/benmosher/eslint-plugin-import/issues/788

### CODE REVIEW

**Comment by mieszko4** [comment]
Not sure why tests are failing. `master` is failing for me, too.

**Comment by ljharb** [comment]
nodejs.org was down earlier today. I'll rerun.

**Comment by mieszko4** [comment]
Not a problem of nodejs.org.
Locally my tests also fail for my commit and even for master commit.
I even tried to follow the commands from this successful build (https://ci.appveyor.com/project/benmosher/eslint-plugin-import/build/1696/job/5gwjncjqkyj0srii) that I've found using the same npm/node versions and it locally fails with 2 pending and 6 errors. I am on Linux.

**Comment by benmosher** [comment]
as noted in #788, I don't know if this is a good idea as some things hold the plugin in memory for an extended period. would need to periodically reload or at least check file modified time / hash of contents for changes. the latter would still be a major perf gain.

also: looks like babel is reporting some things as syntax errors that weren't before, thus the test fails

**Comment by ljharb** [comment]
@mieszko4 not sure if this is still relevant; but it needs a rebase. Please mark it as ready for review when it's so.

**Comment by mieszko4** [comment]
@ljharb I will close it, It's been 4 years so I do not think it is relevant anymore.

**Pull request closed without merging**
