### PR TITLE
first draft of CONTRIBUTING.md

### LINKED ISSUE #257: CONTRIBUTING.md
The time has come for a contributing guide.

Plan:
- [x] find a good example
- [x] copy it with attribution

### PR DESCRIPTION
**Pull request by benmosher**
Given the recent uptick in interest, I figure the time has come to get something like this into `master`. Feels a little goofy to do something like this for a project that is just a plugin for something much larger, but at the same time, this is my primary open source project and it's been getting a lot of great contributions lately.

Comments are encouraged. I've not tried to write anything like this before and in general my written voice can be confusing and pedantic at the best of times.

(closes #257)

### CODE REVIEW

**Comment by kentcdodds** [comment]
You might checkout [makeapullrequest.com](http://makeapullrequest.com) and consider including that.

See also: https://github.com/nayafia/contributing-template

:+1:

**Comment by jfmengels** [comment]
I think it's really good, especially for a first draft. I especially like the tone of it.

It's a big block of text, but it does not feel like a huge todo list (not: I did read it as a reviewer, not a contributor) [this one](https://github.com/kentcdodds/eslint-find-new-rules/blob/master/CONTRIBUTING.md) (which is very good too, especially with the really friendly tone, but there is a huge list of items in the todo list. Even though some are not real todos, but they feel like it).

I think that it might be a good idea to have the checklist at the top of the README though, maybe with a `tl;dr` comment, and putting an extra emphasis (putting it in bold or before the list) on `Remember, you don't need to do it all yourself; any of these are helpful!`. Especially helpful to people who are finishing their PR and want to re-check the todo list.

I'd put that at the top so that readers can quickly see what they need to do contribute. Having a big block of text can scare the reader off, and this could set their expectations quickly.

That said, great tone, great work :)

cc @ta2edchimp who might be interested in this too ;)

**Comment by ta2edchimp** [comment]
The `CONTRIBUTING.md` is really good! Especially including a _Code of Conduct_ is a great idea!

@jfmengels thanks for letting me know of this!

**Comment by jfmengels** [comment]
This still looks very good to me, shall we merge this?

**Pull request merged**
