### PR TITLE
Add support for Webpack 2 renamed modules key

### PR DESCRIPTION
**Pull request by pascalduez**
Hi,

just wanted to start the ball rolling, there most likely will be more work needed to fully support Webpack 2, but that very simple addition is already doing it for me on a project with custom import paths.

Rough changelog: https://gist.github.com/sokra/27b24881210b56bbaff7#resolving-options

If you feel that's okay for a start, I'll update the tests ?

Refs #265

### CODE REVIEW

**Comment by benmosher** [comment]
I like the simplicity. I don't have any Webpack 2 projects to check against, so I'll take your word for it. 😎

New tests would be much appreciated. Probably a clone of the existing moduleDirectories tests would be a good start, assuming the semantics match.

**Comment by benmosher** [comment]
Heads up: this will probably not be mergeable after I merge #345. 

I think it will make more sense to make a `webpack-2` resolver, see my notes on #345.

**Comment by michael-wolfenden** [comment]
@benmosher 

In webpack2, [resolve.root](https://webpack.github.io/docs/configuration.html#resolve-root) has been merged into the [modules option](https://gist.github.com/sokra/27b24881210b56bbaff7#resolving-options), however the commit doesn't handle this.

webpack
```js
resolve: {
    root: PATHS.appDir
}
```

webpack2
```js
resolve: {
    modules: [
        'node_modules',
        PATHS.appDir,
    ],
},
```

I had to add the following code to make this work, the assumption being that root resolves are absolute paths

```js
// Webpack >= 2
var rootPaths = get(webpackConfig, ['resolve', 'modules'], []).filter(path.isAbsolute);
paths = paths.concat(rootPaths)
```

**Comment by gausie** [comment]
Now that #345 is merged, how are you feeling about this @benmosher?

**Comment by benmosher** [comment]
I think I'd probably opt for a `webpack2` resolver, mostly because there is a factory to build `resolve` from config that would be nice to leverage for ongoing correctness.

I can maintain it here (another PR, anyone?), or someone in the community can maintain it independently. Either way works for me.

I don't think I would keep this duck-typed version. I'm not sure how it would integrate with the current `webpack` resolver.

**Comment by pascalduez** [comment]
Let's close this and do it the proper way :)

**Pull request closed without merging**
