### PR TITLE
chore(package): update `enhanced-resolve`

### PR DESCRIPTION
**Pull request by evilebottnawi**
Just update `enhanced-resolve` package

### CODE REVIEW

**Comment by j-f1** [comment]
Build failure:

```
  1) config finds the first config with a resolve section:
     AssertionError: expected { found: false } to have a property 'path'
      at Context.<anonymous> (test/config.js:46:60)
  2) config finds the first config with a resolve section when config is an array of config objects:
     AssertionError: expected { found: false } to have a property 'path'
      at Context.<anonymous> (test/config.js:80:60)
  3) extensions respects the defaults:
     AssertionError: expected { found: false } to have a property 'path'
      at Context.<anonymous> (test/extensions.js:13:44)
  4) fallback supports definition as an array:
     AssertionError: expected { found: false } to have a property 'path'
      at Context.<anonymous> (test/fallback.js:25:8)
  5) packageMains captures jsnext:
     AssertionError: expected { found: false } to have a property 'path'
      at Context.<anonymous> (test/packageMains.js:18:47)
  6) packageMains captures webpack:
      AssertionError: expected '/home/travis/build/benmosher/eslint-plugin-import/resolvers/webpack/test/package-mains/webpack/index.js' to equal '/home/travis/build/benmosher/eslint-plugin-import/resolvers/webpack/test/package-mains/webpack/webpack.js'
      + expected - actual
      -/home/travis/build/benmosher/eslint-plugin-import/resolvers/webpack/test/package-mains/webpack/index.js
      +/home/travis/build/benmosher/eslint-plugin-import/resolvers/webpack/test/package-mains/webpack/webpack.js
      
      at Context.<anonymous> (test/packageMains.js:24:11)
  7) packageMains captures jam (array path):
      AssertionError: expected '/home/travis/build/benmosher/eslint-plugin-import/resolvers/webpack/test/package-mains/jam/index.js' to equal '/home/travis/build/benmosher/eslint-plugin-import/resolvers/webpack/test/package-mains/jam/jam.js'
      + expected - actual
      -/home/travis/build/benmosher/eslint-plugin-import/resolvers/webpack/test/package-mains/jam/index.js
      +/home/travis/build/benmosher/eslint-plugin-import/resolvers/webpack/test/package-mains/jam/jam.js
      
      at Context.<anonymous> (test/packageMains.js:29:11)
  8) packageMains always defers to jsnext:main, regardless of config:
     AssertionError: expected { found: false } to have a property 'path'
      at Context.<anonymous> (test/packageMains.js:43:84)
  9) plugins work:
     AssertionError: expected { found: false } to have a property 'found' of true, but got false
      at Context.<anonymous> (test/plugins.js:18:30)
  10) plugins is correct:
     AssertionError: expected { found: false } to have a property 'path'
      at Context.<anonymous> (test/plugins.js:22:30)
  11) plugins work with alias:
     AssertionError: expected { found: false } to have a property 'found' of true, but got false
      at Context.<anonymous> (test/plugins.js:27:35)
  12) root supports definition as an array:
     AssertionError: expected { found: false } to have a property 'path'
      at Context.<anonymous> (test/root.js:21:8)
```

**Comment by evilebottnawi** [comment]
@j-f1 strange, locally all fine :confused:

**Comment by evilebottnawi** [comment]
@ljharb hm, maybe you are right

**Comment by benmosher** [comment]
closing this for now. fwiw I think the webpack resolver tries to use a peer `webpack`'s `enhanced-resolve` if it is installed as a dev dependency within the same project. so this version is a backup, intended to go unused.

**Pull request closed without merging**
