### PR TITLE
Update README.md for #1256

### PR DESCRIPTION
**Pull request by kirill-konshin**

### CODE REVIEW

**Comment by kirill-konshin** [comment]
You're right! In fact, the recommended config should also be updated to this new naming. Hold on ) I will push an update.

**Comment by kirill-konshin** [comment]
Done. Pls squash before merge )))

**Comment by benmosher** [comment]
That is my bad for totally failing to remember the right package name off the top of my head 😳 

I double-checked just now and updated both to the actual `npm` name. Thanks for this!

**Comment by kirill-konshin** [comment]
Lol, it happens ) good that it was captured. What's the release ETA?

**Comment by marcneander** [comment]
Would love a new release with this 👍

**Comment by EvertEt** [comment]
Any idea about the ETA for a new version including `@eslint/typescript-parser`?

**Comment by kirill-konshin** [comment]
Ping...

**Comment by kirill-konshin** [comment]
Are you guys collecting some additional changes before releasing this? Are there any roadblocks?

**Comment by Teoxoy** [comment]
I would like to see a new version with this too! 👍

**Comment by kirill-konshin** [comment]
Any news regarding the release? Last was on Jan 29... Also there's a fix for #1282 merged this morning...

**Comment by mcmar** [comment]
@ljharb This has been in the README for 3 months now, but it still hasn't been released to npm. As a result, anyone who follows the README on github is getting broken builds.
Reported here: https://github.com/benmosher/eslint-plugin-import/issues/1285
Can you please do a release?

**Comment by ljharb** [comment]
That’s always a risk; one should check the readme for the latest released tag, not master.

A release will happen when time permits; further commenting doesn’t make that happen any faster.

**Comment by kirill-konshin** [comment]
Just to make it clear, is there any particular reason that holds off the release other than lack of time to do it? Is there any help needed?

**Comment by ljharb** [comment]
That’s pretty much it; it’s not something that i think can be helped at this time, unfortunately.

**Comment by kirill-konshin** [comment]
@ljharb do you mind considering to add more collaborators who can release? No offense, but 2+ months since last release is a lot. Looks like tests are passing but the build is failing, is this the issue that holds release? Are there any other pre-release checks that have to be done?

**Pull request merged**
