### PR TITLE
Support Node v6

### PR DESCRIPTION
**Pull request by benmosher**
Track progress against this PR. 

Known issues:

- #272: don't pass null to path functions

### CODE REVIEW

**Comment by strawbrary** [comment]
v6 is on Travis now so you should be good to retry.

I haven't encountered any issues on v6 besides the null path one.

**Comment by jfmengels** [comment]
I re-ran the tests, and they're good to go :)

**Comment by benmosher** [comment]
Interesting, if no tests are failing, that means there is no test that covers #272? Which seems weird, I would think at least one test would try to resolve a builtin.

So feels like we need at least one test for that breaks a la #272 before merging? (after fixing it, too)

**Comment by strawbrary** [comment]
Hmm that is strange. On my local box I get 36 failures when running on v6.0.0. Could someone else try it and see if they get the same?

**Comment by jfmengels** [comment]
It passes all tests on my machine (removed node_modules, `npm i`ed and `npm test`) :confused:

**Comment by benmosher** [comment]
@strawbrary are you on Windows? or OSX?
@jfmengels: same question?

I just added v6 to the Appveyor config to see how Windows takes it.

**Comment by jfmengels** [comment]
Linux Ubuntu here.

**Comment by strawbrary** [comment]
OSX El Capitan

**Comment by strawbrary** [comment]
It seems like `fileExistsWithCaseSync` is never called with a `null` `filepath` under Linux, while it is under OSX and Windows. Any ideas about that?

**Comment by benmosher** [comment]
Yep, that makes sense. I'm on OSX but haven't tried to run locally yet.

**Comment by Salakar** [comment]
Tested on OSX + node v6, now working, also fixes an issue with Webstorm IDE being unable to parse the `<checkstyle/>` XML - for those finding this error randomly lurking up on them 😆

**Pull request merged**
