### PR TITLE
Upgrade debug version of eslint-module-utils

### PR DESCRIPTION
**Pull request by popomore**

### CODE REVIEW

**Comment by popomore** [comment]
Appveyor failed, but not caused by this PR, it seems coveralls do some wrong things.

**Comment by popomore** [comment]
cc @benmosher

**Comment by popomore** [comment]
Ping @benmosher

**Comment by popomore** [comment]
@benmosher When will release next version?

**Comment by benmosher** [comment]
not sure, have to investigate #863 first 😩

**Comment by popomore** [comment]
@benmosher bad news, hope this issue could be resolved soon.

**Pull request merged**
