### PR TITLE
Support webpack 2.2-rc

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@benmosher I can't work out why appveyor is failing

**Comment by graingert** [comment]
This seems to be what the official (under the webpack project on github) loaders and plugins do

**Comment by graingert** [comment]
@jfmengels @benmosher any update on merging this?

**Comment by ChaseBro** [comment]
Is there anything additional required here? I would love to see this get merged as it's blocking the upgrade to Webpack 2. Happy to help if there's anything else needed.

**Comment by graingert** [comment]
@benmosher this seems to be blocking a fair few projects...

**Comment by ChaseBro** [comment]
Will this be merged? It's been almost 3 weeks since it was originally submitted (admittedly including the holidays), but I would really love to keep using this plugin if at all possible.

**Comment by graingert** [comment]
@benmosher now that extract-text-webpack-plugin is out. This is the last project blocking me from enjoying the glory of webpack 2rc.

**Comment by benmosher** [comment]
published as v0.8.1 of the webpack resolver 😎

**Comment by benmosher** [comment]
btw, thanks for reviewing @jfmengels!

**Comment by jfmengels** [comment]
> btw, thanks for reviewing @jfmengels!

No problem. I'll try to do some more, I've been neglecting too many projects lately.

@graingert Do we need to make a similar change for webpack 2.2.0-alpha and webpack 2.2.0?

**Comment by graingert** [comment]
should just work for 2x

**Comment by jfmengels** [comment]
Sorry. Did you mean that we should make a change to support webpack 2-x-x, or that this is already good? The former, right?

**Comment by graingert** [comment]
@jfmengels `^2.1.0` means` >=2.1.0 <3.0.0`

**Pull request merged**
